services:
  mongo:
    image: mongo:8.0.9
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - ./data/db:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - mynet
 
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - mongo
    networks:
      - mynet
 
  backend:
    build: ./backend
    ports:
      - "8082:80"
    depends_on:
      - mongo
    networks:
      - mynet
 
networks:
  mynet:
    driver: bridge